export default class TrialsService {
  SERVICE_PATH = '/trials';

  trials = [
    {
      id: 1,
      name: 'trial 1',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 2,
      name: 'trial 2',
      progress: 22,
      status: 0,
      enrolled: 350,
      total: 500,
      countries: ['IT'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 3,
      name: 'trial 3',
      progress: 33,
      status: 2,
      enrolled: 250,
      total: 600,
      countries: ['FR', 'ES'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 4,
      name: 'trial 4',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 5,
      name: 'trial 5',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 6,
      name: 'trial 6',
      progress: 20,
      status: 2,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 7,
      name: 'trial 7',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 8,
      name: 'trial 8',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 9,
      name: 'trial 9',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 10,
      name: 'trial 10',
      progress: 22,
      status: 0,
      enrolled: 350,
      total: 500,
      countries: ['IT'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 11,
      name: 'trial 11',
      progress: 33,
      status: 2,
      enrolled: 250,
      total: 600,
      countries: ['FR', 'ES'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 12,
      name: 'trial 12',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 13,
      name: 'trial 13',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 14,
      name: 'trial 14',
      progress: 20,
      status: 2,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 15,
      name: 'trial 15',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 16,
      name: 'trial 16',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 17,
      name: 'trial 17',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 18,
      name: 'trial 18',
      progress: 22,
      status: 0,
      enrolled: 350,
      total: 500,
      countries: ['IT'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 19,
      name: 'trial 19',
      progress: 33,
      status: 2,
      enrolled: 250,
      total: 600,
      countries: ['FR', 'ES'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 20,
      name: 'trial 20',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 21,
      name: 'trial 21',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 22,
      name: 'trial 22',
      progress: 20,
      status: 2,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 23,
      name: 'trial 23',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 24,
      name: 'trial 24',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 1,
      name: 'trial 1',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 2,
      name: 'trial 2',
      progress: 22,
      status: 0,
      enrolled: 350,
      total: 500,
      countries: ['IT'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 3,
      name: 'trial 3',
      progress: 33,
      status: 2,
      enrolled: 250,
      total: 600,
      countries: ['FR', 'ES'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 4,
      name: 'trial 4',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 5,
      name: 'trial 5',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 6,
      name: 'trial 6',
      progress: 20,
      status: 2,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 7,
      name: 'trial 7',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 8,
      name: 'trial 8',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 9,
      name: 'trial 9',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 10,
      name: 'trial 10',
      progress: 22,
      status: 0,
      enrolled: 350,
      total: 500,
      countries: ['IT'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 11,
      name: 'trial 11',
      progress: 33,
      status: 2,
      enrolled: 250,
      total: 600,
      countries: ['FR', 'ES'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 12,
      name: 'trial 12',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 13,
      name: 'trial 13',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 14,
      name: 'trial 14',
      progress: 20,
      status: 2,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 15,
      name: 'trial 15',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 16,
      name: 'trial 16',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 17,
      name: 'trial 17',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 18,
      name: 'trial 18',
      progress: 22,
      status: 0,
      enrolled: 350,
      total: 500,
      countries: ['IT'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 19,
      name: 'trial 19',
      progress: 33,
      status: 2,
      enrolled: 250,
      total: 600,
      countries: ['FR', 'ES'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 20,
      name: 'trial 20',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 21,
      name: 'trial 21',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 22,
      name: 'trial 22',
      progress: 20,
      status: 2,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 23,
      name: 'trial 23',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 24,
      name: 'trial 24',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 1,
      name: 'trial 1',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 2,
      name: 'trial 2',
      progress: 22,
      status: 0,
      enrolled: 350,
      total: 500,
      countries: ['IT'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 3,
      name: 'trial 3',
      progress: 33,
      status: 2,
      enrolled: 250,
      total: 600,
      countries: ['FR', 'ES'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 4,
      name: 'trial 4',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 5,
      name: 'trial 5',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 6,
      name: 'trial 6',
      progress: 20,
      status: 2,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 7,
      name: 'trial 7',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 8,
      name: 'trial 8',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 9,
      name: 'trial 9',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 10,
      name: 'trial 10',
      progress: 22,
      status: 0,
      enrolled: 350,
      total: 500,
      countries: ['IT'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 11,
      name: 'trial 11',
      progress: 33,
      status: 2,
      enrolled: 250,
      total: 600,
      countries: ['FR', 'ES'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 12,
      name: 'trial 12',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 13,
      name: 'trial 13',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 14,
      name: 'trial 14',
      progress: 20,
      status: 2,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 15,
      name: 'trial 15',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 16,
      name: 'trial 16',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 17,
      name: 'trial 17',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 18,
      name: 'trial 18',
      progress: 22,
      status: 0,
      enrolled: 350,
      total: 500,
      countries: ['IT'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 19,
      name: 'trial 19',
      progress: 33,
      status: 2,
      enrolled: 250,
      total: 600,
      countries: ['FR', 'ES'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 20,
      name: 'trial 20',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 21,
      name: 'trial 21',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 22,
      name: 'trial 22',
      progress: 20,
      status: 2,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 23,
      name: 'trial 23',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 24,
      name: 'trial 24',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 1,
      name: 'trial 1',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 2,
      name: 'trial 2',
      progress: 22,
      status: 0,
      enrolled: 350,
      total: 500,
      countries: ['IT'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 3,
      name: 'trial 3',
      progress: 33,
      status: 2,
      enrolled: 250,
      total: 600,
      countries: ['FR', 'ES'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 4,
      name: 'trial 4',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 5,
      name: 'trial 5',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 6,
      name: 'trial 6',
      progress: 20,
      status: 2,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 7,
      name: 'trial 7',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 8,
      name: 'trial 8',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 9,
      name: 'trial 9',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 10,
      name: 'trial 10',
      progress: 22,
      status: 0,
      enrolled: 350,
      total: 500,
      countries: ['IT'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 11,
      name: 'trial 11',
      progress: 33,
      status: 2,
      enrolled: 250,
      total: 600,
      countries: ['FR', 'ES'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 12,
      name: 'trial 12',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 13,
      name: 'trial 13',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 14,
      name: 'trial 14',
      progress: 20,
      status: 2,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 15,
      name: 'trial 15',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 16,
      name: 'trial 16',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 17,
      name: 'trial 17',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 18,
      name: 'trial 18',
      progress: 22,
      status: 0,
      enrolled: 350,
      total: 500,
      countries: ['IT'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 19,
      name: 'trial 19',
      progress: 33,
      status: 2,
      enrolled: 250,
      total: 600,
      countries: ['FR', 'ES'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 20,
      name: 'trial 20',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 21,
      name: 'trial 21',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 22,
      name: 'trial 22',
      progress: 20,
      status: 2,
      enrolled: 250,
      total: 500,
      countries: ['GR', 'RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 23,
      name: 'trial 23',
      progress: 20,
      status: 0,
      enrolled: 250,
      total: 500,
      countries: ['RO'],
      started: new Date().toISOString().slice(0, 10),
    },
    {
      id: 24,
      name: 'trial 24',
      progress: 20,
      status: 1,
      enrolled: 250,
      total: 500,
      countries: ['GR'],
      started: new Date().toISOString().slice(0, 10),
    },
  ];

  constructor(DSUStorage) {
    this.DSUStorage = DSUStorage;
  }

  getTrials() {
    return this.trials;
  }

  getTrial(id) {
    return this.trials.find((x) => x.id === id);
  }
}
